"""Starter CARC + RARC reference data.

Official verbiage sourced from X12/WPC published lists. This is not the
full catalog (~400 CARC + ~700 RARC codes) — just the codes commonly seen
in ambulatory OB/GYN claim remittances. Add more codes via the seed
script or the `/adjustment-codes` API as needed.
"""

# (code, official_verbiage) — Claim Adjustment Reason Codes
CARC_CODES = [
    ("1", "Deductible Amount"),
    ("2", "Coinsurance Amount"),
    ("3", "Co-payment Amount"),
    ("4", "The procedure code is inconsistent with the modifier used."),
    ("6", "The procedure/revenue code is inconsistent with the patient's age."),
    ("11", "The diagnosis is inconsistent with the procedure."),
    ("16", "Claim/service lacks information or has submission/billing error(s)."),
    ("18", "Exact duplicate claim/service."),
    ("22", "This care may be covered by another payer per coordination of benefits."),
    ("23", "The impact of prior payer(s) adjudication including payments and/or adjustments."),
    ("24", "Charges are covered under a capitation agreement/managed care plan."),
    ("26", "Expenses incurred prior to coverage."),
    ("27", "Expenses incurred after coverage terminated."),
    ("29", "The time limit for filing has expired."),
    ("31", "Patient cannot be identified as our insured."),
    ("39", "Services denied at the time authorization/pre-certification was requested."),
    ("45", "Charge exceeds fee schedule/maximum allowable or contracted/legislated fee arrangement."),
    ("49", "This is a non-covered service because it is a routine/preventive exam or a diagnostic/screening procedure done in conjunction with a routine/preventive exam."),
    ("50", "These are non-covered services because this is not deemed a 'medical necessity' by the payer."),
    ("54", "Multiple physicians/assistants are not covered in this case."),
    ("96", "Non-covered charge(s)."),
    ("97", "The benefit for this service is included in the payment/allowance for another service/procedure that has already been adjudicated."),
    ("109", "Claim/service not covered by this payer/contractor. You must send the claim/service to the correct payer/contractor."),
    ("119", "Benefit maximum for this time period or occurrence has been reached."),
    ("125", "Submission/billing error(s)."),
    ("129", "Prior processing information appears incorrect."),
    ("140", "Patient/Insured health identification number and name do not match."),
    ("146", "Diagnosis was invalid for the date(s) of service reported."),
    ("150", "Payer deems the information submitted does not support this level of service."),
    ("151", "Payment adjusted because the payer deems the information submitted does not support this many/frequency of services."),
    ("167", "This (these) diagnosis(es) is (are) not covered."),
    ("170", "Payment is denied when performed/billed by this type of provider."),
    ("181", "Payment adjusted because this procedure code was invalid on the date of service."),
    ("183", "The referring provider is not eligible to refer the service billed."),
    ("185", "The rendering provider is not eligible to perform the service billed."),
    ("197", "Precertification/authorization/notification/pre-treatment absent."),
    ("198", "Precertification/authorization exceeded."),
    ("204", "This service/equipment/drug is not covered under the patient's current benefit plan."),
    ("226", "Information requested from the Billing/Rendering Provider was not provided or not provided timely or was insufficient/incomplete."),
    ("227", "Information requested from the patient/insured/responsible party was not provided or was insufficient/incomplete."),
    ("234", "This procedure is not paid separately."),
    ("242", "Services not provided by network/primary care providers."),
    ("243", "Services not authorized by network/primary care providers."),
    ("252", "An attachment/other documentation is required to adjudicate this claim/service."),
    ("253", "Sequestration - reduction in federal payment."),
    ("256", "Service not payable per managed care contract."),
]

# (code, official_verbiage) — Remittance Advice Remark Codes
RARC_CODES = [
    ("M15", "Separately billed services/tests have been bundled as they are considered components of the same procedure. Separate payment is not allowed."),
    ("M25", "The information furnished does not substantiate the need for this level of service. If you believe the service should have been fully covered as billed, or if you did not know and could not reasonably have been expected to know that we would not pay for this level of service, or if you notified the patient in writing in advance that we would not pay for this level of service and he/she agreed in writing to pay, ask us to review your claim within 120 days of the date of this notice. If you do not request an appeal, we will, upon application from the patient, refund any amount paid by the patient for this level of service."),
    ("M86", "Service denied because payment already made for same/similar procedure within set time frame."),
    ("M127", "Missing patient medical record for this service."),
    ("MA04", "Secondary payment cannot be considered without the identity of or payment information from the primary payer. The information was either not reported or was illegible."),
    ("MA63", "Missing/incomplete/invalid principal diagnosis."),
    ("MA64", "Our records indicate that we should be the third payer for this claim. We cannot process this claim until we have received payment information from the primary and secondary payers."),
    ("MA67", "Correction to a prior claim."),
    ("MA120", "Missing/incomplete/invalid CLIA certification number."),
    ("N4", "Missing/Incomplete/Invalid prior insurance carrier EOB."),
    ("N10", "Adjustment based on the findings of a review organization/professional consult/manual adjudication/medical advisor/dental advisor/peer review."),
    ("N30", "Patient ineligible for this service."),
    ("N115", "This decision was based on a Local Coverage Determination (LCD)."),
    ("N130", "Consult plan benefit documents/guidelines for information about restrictions for this service."),
    ("N192", "Patient is a Medicaid/Qualified Medicare Beneficiary."),
    ("N290", "Missing/incomplete/invalid rendering provider primary identifier."),
    ("N382", "Missing/incomplete/invalid patient identifier."),
    ("N418", "Misrouted claim. See the payer's claim submission instructions."),
    ("N432", "Adjustment based on a Recovery Audit."),
    ("N456", "Missing/incomplete/invalid type of bill."),
    ("N522", "Duplicate of a claim processed, or to be processed, as a crossover claim."),
    ("N563", "Missing required claim information. Resubmit claim with the missing information."),
    ("N657", "This should be billed with the appropriate code for these services."),
    ("N674", "Not covered unless a pre-requisite procedure/service has been provided."),
]
